project:
  type: website

website:
  title: "무한포옹 (無限抱擁)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mugen-Houyou
      - icon: twitter
        href: about:blank
format:
  html:
    theme: cosmo
    css: styles.css

