project:
  type: website
  output-dir: docs
  
website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mugen-Houyou
      - icon: twitter
        href: about:blank
format:
  html:
    theme: cosmo
    css: styles.css

