project:
  type: website
  output-dir: docs
  
website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mugen-Houyou
format:
  html:
    theme: 
      light: [flatly, theme-light.scss]
      dark: darkly
    css: styles.css

